import smtplib

server = smtplib.SMTP('smtp.gmail.com', 587)

server.starttls()

server.login('suhasinigaikwad10@gmail.com','scijmowhpsmxjitb')

server.sendmail('suhasinigaikwad10@gmail.com', 'suhanigaikwad10@gmail.com', 'Hello dear,\n This is autogenerated mail by using python.\n\n\n Thanks & Regards,\n Suha')
print("mail sent")